config/routes.rb
Rails.application.routes.draw do


  resources :posts do
    resources :comments, only: [:create]
  end

  get '/register', to: 'users#new'
  resources :users, only: [:create]

  get '/sign_in', to: 'sessions#new'
  get '/sign_out', to: 'sessions#destroy'
  resources :sessions, only: [:create]

  resources :likes, only: [:create, :destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  belongs_to :parent, class_name: 'Comment', optional: true
  has_many :comments, foreign_key: :parent_id
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, uniqueness: { scope: [:likeable_id, :likeable_type] }
  belongs_to :user
  belongs_to :likeable, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_many :comments
  has_many :likes, as: :likeable

end

app/models/user.rb
class User < ApplicationRecord

  validates :email, uniqueness: true
  validates :email, presence: true
  has_many :posts
  has_many :comments
  has_many :likes

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user

  def ensure_current_user
    if current_user.nil?
      redirect_to "/"
    else
    end
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = current_user.comments.new(comment_params)
    if @comment.save
      redirect_to post_path(params[:post_id])
    else
      redirect_to new_post_path
    end
  end

  private

  def comment_params
    params.require(:comment)
          .permit(:content, :parent_id)
          .merge(post_id: params[:post_id])
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @like = current_user.likes.new(like_params)
    if @like.save
    end
    redirect_to @like.post
  end

  def destroy
    @like = current_user.likes.find(params[:id])
    post = @like.post
    @like .destroy
    redirect_to post

  end

  private

  def like_params
    params.require(:like).permit(:post_id)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [ :edit, :update, :destroy ]
  before_action :ensure_current_user

  # GET /posts or /posts.json
  def index
    @posts = current_user.posts
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post = Post.find(params[:id])
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end


  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = current_user.posts.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: user_params[:email])
    if @user && @user.password == user_params[:password]
      session[:user_id] = @user.id
      redirect_to posts_path
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to sign_in_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to posts_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<article>

  <p><%= comment.content %></p>
  <small>Posted by: <%= comment.user.email %></small>

  <a href="#" class="comment-form-display">reply</a>
  <div class="comment-form">
    <%= render partial: 'comments/form', locals: { post: comment.post, parent: comment }%>
  </div>

  <hr />

  <div class="sub-comment">
    <%= render comment.comments.order(id: :desc) %>
  </div>
</article>

<script>
  document.querySelectorAll('.comment-form-display').forEach((el) => {
      el.addEventListener('click', (ev) => {
          ev.preventDefault();
          el.nextElementSibling.style = 'display: block;'
      })
  })
</script>

app/views/comments/_form.html.erb
<form action="<%= post_comments_path(post) %>" method="post">
  <input type="hidden" name="authenticity_token">
  <% if !parent.nil? %>
    <input type="hidden" name="comment[parent_id]" value="<%= parent.id %>">
  <% end %>

  <div>
    <textarea name="comment[content]" rows="3" cols="20"></textarea>
  </div>

  <input type="submit" value="Submit">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Petspro</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if current_user %>
      Hi <%= current_user.email %>

      <%= link_to "Log out", sign_out_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
 <table class="table">
   <tbody>
   <tr>
     <td><%= post.title %></td>
     <td><%= post.description %></td>
     <td></td>
   </tr>
   </tbody>
 </table>

app/views/posts/edit.html.erb
 <h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back", posts_path %>
</div>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<%= @post.likes.count %> Like
<% like = current_user.likes.find_by(post: @post) %>
<% if like.nil? %>
  <%= button_to "Like", likes_path, params: { like:{ post_id: @post.id }}, method: :post %>
<% else %>
  <%= button_to "Unlike", like_path(like), method: :delete %>
<% end %>

<p>
  <strong>Comments:</strong>

  <%= render @post.comments.where(parent_id: nil).includes(:user).order(id: :desc) %>
  <%= render partial: 'comments/form', locals: { post: @post, parent: nil } %>
</p>

  <%= link_to "Edit", edit_post_path(@post) %> |
  <%= link_to "Back", posts_path %>

app/views/users/new.html.erb
<h1>Register</h1>

<form action="/users" method="post" >
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="email">Email</label> <br>
  <input type="email" id="email" name="user[email]" value="<%= @user.email %>"> <br><br>

  <label for="password">Password</label> <br>
  <input type="password" id="password" name="user[password]"> <br><br>

  <input type="submit" value="Register">

</form>